### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by Surya-Mandapati-19** [Raviteja7Lanka/Inventory_Management_SE_Project#23]
I am trying to write API for customers and suppliers table, however, during run-time, I got the following error. Would appreciate your help.

2022/03/02 17:47:11 http: panic serving [::1]:60990: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1802 +0xb9
panic({0x7ff785b802e0, 0x7ff785b2e4b0})
        C:/Program Files/Go/src/runtime/panic.go:1047 +0x266
main.getAllSupplier({0x7ff785c5c330, 0xc00023a0e0}, 0xc000202ae0)
        C:/Users/mvsnr/OneDrive - University of Florida/Desktop/Inventory_Management_SE_Project/server/ordersAPI.go:123 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc00021a600, {0x7ff785c5c330, 0xc00023a0e0}, 0x100000000000010)
        C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001323c0, {0x7ff785c5c330, 0xc00023a0e0}, 0xc000060000)
        C:/Users/mvsnr/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.(*ServeMux).ServeHTTP(0x0, {0x7ff785c5c330, 0xc00023a0e0}, 0xc000060000)
        C:/Program Files/Go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x7ff785c5b6d0}, {0x7ff785c5c330, 0xc00023a0e0}, 0xc000060000)
        C:/Program Files/Go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc00005a000, {0x7ff785c5dda0, 0xc0001b7620})
        C:/Program Files/Go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        C:/Program Files/Go/src/net/http/server.go:3034 +0x4e8

**Comment by Surya-Mandapati-19** [comment]
I have modified database to solve this issue
